services:
  - type: web
    name: multilingual-voice-agent
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: GEMINI_API_KEY
        sync: false
      - key: ASSEMBLYAI_API_KEY
        sync: false
      - key: MURF_API_KEY
        sync: false
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
