services:
  - type: web
    name: multilingual-voice-agent
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
